### ISSUE TITLE
How is 'babel.js' generated?

### ISSUE THREAD

**Issue by dchambers** [robertsundstrom/SystemJS-Node-Starter-Template#1]
Hi @robertsundstrom, thanks for providing this repo as I was struggling to get SystemJS working directly within Node.js once I started using ES6. Could you possibly clarify where you got `src/babel/babel.js` from, or how you generated it, as this is not presently mentioned in the `README.md`?

**Comment by dchambers** [comment]
Not to worry. I assumed you'd used browserify, but didn't know what to set `-s` to, so I chanced that it was simply `babel`, and it worked!

Here's the command I used:

```
browserify node_modules/babel/index.js -s babel -o dist/babel.js
```

**Comment by robertsundstrom** [comment]
Sorry for not respondig. I've been busy.

Alright. It should work without Browserify. 

But I don't remember writing this in the Read Me:

npm install jspm@beta (to install the latest JSPM which this project depend on)

Then:

jspm install (in src)
run.bat

I might have missed something.

**Comment by dchambers** [comment]
Hi @robertsundstrom, it doesn't actually need browserify as you've pre-browserified Babel &mdash; within the `src/babel` directory. I just wanted to do the browserify step in my `pre publish` hook, which I've now managed to do, and everything's working well.

Thanks for pointing me in the right direction :+1:

**Comment by robertsundstrom** [comment]
(y) Good. 

Btw. I have another project that is more up-to-date https://github.com/robertsundstrom/knockoutjs-express-es6.

These two projects share a lot in common.

You should check that.
